# Generated by Django 5.0.1 on 2024-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
